# Site settings
title: Your SketchSpace Site    #   Please change this.
tagline: "This website is running on SketchSpace"   #   You can change this.
url: "http://emilsayahi.github.io/SketchSpace/" # The base hostname & protocol for your site. Use it if you need absolute URL's.
author: Your Name   #   This name...might be real?
disqus_shortname:   ""  #   Your Disqus shortname for comic embeds.
comments: false #  If 'true', then your comics will have Disqus comments enabled. If 'false' (default), then there will be no comments section.
post_title_rendered: true # Determines if the title of each comic post is rendered. Default is 'true'.
web_title_is_img: true # Determines if the title of the website is an image or text. Default is 'true'.
nav_buttons_is_img: false #    Determines if the navigation buttons of the site are images or unicode. Default is 'false'.
web_title_path: "/img/logo_cropped.png" # If the website title is an image, then the image at this path will be supplied.
nav_button_path: /path/to/ # If the navigation buttons are images, then the buttons will be retrieved from this folder. Buttons should be named "nav_left.png" and "nav_right.png".


# Social (optional)
facebook: https://www.facebook.com/zuck    #   URL to your Facebook
twitter: https://twitter.com/twitter #   URL to your Twitter
github: https://github.com/defunkt  #   URL to your GitHub
googleplus: https://plus.google.com/+google   #   URL to your Google+ (ha!)
instagram: https://www.instagram.com/instagram/   #   URL to your Instagram

# Contact
phone: "+1 800-555-0100" #  This number isn't real.
email: "example@example.com" #  This e-mail isn't real.

#Jekyll settings
collections:
  posts:
    title: posts
    output: true
baseurl: "/SketchSpace" #   If you're not hosting in a folder, set this to blank. If not, put the FOLDER ONLY into the baseurl field. Example: "/comics"
markdown: kramdown
gems:
- jekyll-paginate
permalink: pretty
paginate: 1
paginate_path: page:num

#   Use this for when you're hosting a production branch.
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
