# Site settings
title: Your SketchSpace Site    #   Please change this.
tagline: "This website is running on SketchSpace"   #   You can change this.
url: "http://emilsayahi.github.io/SketchSpace/" # The base hostname & protocol for your site. Use it if you need absolute URL's.
author: Your Name   #   This name...might be real?
comments: no #  If 'yes', then your comics will have Disqus comments enabled. If 'no' (default), then there will be no comments section.
post_title_is_img: no # Determines if the title of each comic post is an image or text. Default is 'no'.
web_title_is_img: yes # Determines if the title of the website is an image or text. Default is 'yes'.
nav_buttons_is_img: no #    Determines if the navigation buttons of the site are images or unicode. Default is 'no'.
post_title_path: /path/to/img # If the post title is an image, then the image at this path will be supplied. Leave this blank if the title is in the comic.
web_title_path: /path/to/img # If the website title is an image, then the image at this path will be supplied.
nav_button_path: /path/to/ # If the navigation buttons are images, then the buttons will be retrieved from this folder. Buttons should be named "nav_left.png" and "nav_right.png".


# Social (optional)
socialimg: /img/social.jpg # Be sure to change this image
facebook: fb-username    #   Your Facebook username
twitter: tw-username #   Your Twitter handle
github: gh-username  #   Your GitHub account name
googleplus: g-username   #   Your Google+ username (ha!)
instagram: ig-username   #   Your Instagram handle

# Contact
phone: "+1 555-111-0100" #  This number isn't real.
email: "example@example.com" #  This e-mail isn't real.

#Jekyll settings
collections:
  posts:
    title: posts
    output: true
baseurl: "/SketchSpace" #   If you're not hosting on a subdomain, set this to blank. If not, put the SUBDOMAIN ONLY into the baseurl field. Example: "/comics"
markdown: kramdown
gems:
- jekyll-paginate
permalink: pretty
paginate: 10
paginate_path: blog/page:num

#   Use this for when you're hosting a production branch.
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
